name: presentation
description: presentation layer
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  data:
    path: ../data
  domain:
    path: ../domain
  go_router: ^6.2.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_gen_runner: ^5.3.0
  go_router_builder: ^1.2.1


# Config flutter_gen
# https://pub.dev/packages/flutter_gen
flutter_gen:
  null_safety: true # Optional (default: true)
  output: lib/generated/ # Optional (default: lib/gen/)
  integrations:
    flutter_svg: true
  assets:
    outputs:
      enable: true
      package_parameter_enabled: true

# Config Intl
# https://docs.flutter.dev/accessibility-and-localization/internationalization
flutter_intl:
  enabled: true
  class_name: S
  main_locale: vi
  arb_dir: lib/l10n
  output_dir: lib/generated/
  use_deferred_loading: false




flutter:
  assets:
    - assets/images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
